# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(498, 670)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 498, 21))
        self.menubar.setObjectName("menubar")
        self.menuRecipe = QtWidgets.QMenu(parent=self.menubar)
        self.menuRecipe.setObjectName("menuRecipe")
        self.menuSettings = QtWidgets.QMenu(parent=self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuHelp = QtWidgets.QMenu(parent=self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtGui.QAction(parent=MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtGui.QAction(parent=MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtGui.QAction(parent=MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionLoad_defaults = QtGui.QAction(parent=MainWindow)
        self.actionLoad_defaults.setObjectName("actionLoad_defaults")
        self.actionEdit = QtGui.QAction(parent=MainWindow)
        self.actionEdit.setEnabled(False)
        self.actionEdit.setObjectName("actionEdit")
        self.actionAbout = QtGui.QAction(parent=MainWindow)
        self.actionAbout.setEnabled(False)
        self.actionAbout.setObjectName("actionAbout")
        self.menuRecipe.addAction(self.actionNew)
        self.menuRecipe.addAction(self.actionOpen)
        self.menuRecipe.addAction(self.actionSave)
        self.menuSettings.addAction(self.actionLoad_defaults)
        self.menuSettings.addAction(self.actionEdit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuRecipe.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuRecipe.setTitle(_translate("MainWindow", "Recipe"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionNew.setText(_translate("MainWindow", "New..."))
        self.actionOpen.setText(_translate("MainWindow", "Open..."))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionLoad_defaults.setText(_translate("MainWindow", "Load defaults"))
        self.actionEdit.setText(_translate("MainWindow", "Edit..."))
        self.actionAbout.setText(_translate("MainWindow", "About"))
